### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by cPolaris** [EternalPhane/UnOnline#1]
- But how do you get the IP address of the device you want to unonline?
- Where did you learn shell scripts? Book? Website?
- Any interesting guys in your school that I can follow?

**Comment by eternalphane** [comment]
- It's just for fun, so... I only use it to kick my roomie offline.
- In fact there's lots of resources online. Searching on **`stackoverflow`** can probably solve the problem I met.
- [_`LiangMingyang`_](https://github.com/LiangMingyang) and [_`renfeisong`_](https://github.com/renfeisong)

**Comment by cPolaris** [comment]
Thanks! Haha. You know who I am, right?...

**Comment by eternalphane** [comment]
...天罡泥垢
